name: Build & Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Flake8
      run: |
        flake8 . --max-line-length=100 --max-complexity 10 --exit-zero
    - name: Test
      run: |
        coverage run --parallel-mode --rcfile=./.coveragerc --source=TrackApp manage.py test --parallel 8
        coverage combine --rcfile=./.coveragerc
        coverage report -m --rcfile=./.coveragerc
