name: Testing

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD}}
          POSTGRES_DB: track_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: psycopg2 prerequisites
      run: sudo apt-get install libpq-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt

    - name: Flake8
      run: |
        flake8 . --max-line-length=100 --max-complexity 10 --ignore=W504,F401

    - name: Run tests
      env:
          DB_NAME: track_db
          DB_USER: postgres
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_PORT: 5432
          DB_HOST: localhost
      run: |
        coverage run --parallel-mode --rcfile=./.coveragerc --source=. manage.py test tests --parallel 4
        coverage combine --rcfile=./.coveragerc
        coverage report -m --rcfile=./.coveragerc >> coverage.txt
        cat coverage.txt
        COVERAGE_STR=`tail -1 coverage.txt | awk '{print $4}'`
        echo $COVERAGE_STR        
        echo "COVERAGE=$(echo ${COVERAGE_STR})" >> $GITHUB_ENV

    - name: Create coverage badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 8064b57379b6b83061b9c28f6b950594
        filename: coverage.json
        label: Test Coverage
        message: ${{ env.COVERAGE }}
        color: green
